<script setup>
  import { ref } from 'vue'
  import { onClickOutside } from '@vueuse/core'
  import { useModalStore } from '../store/modalStore'

  const modalStore = useModalStore()

  const modalRef = ref(null)
  
  onClickOutside(modalRef, (_event) => modalStore.closeModal())
</script>

<template>
  <!-- Modal Overlay -->
  <div class="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-45">
    <!-- Modal Container -->
    <div ref="modalRef" class="z-10 bg-gray-800 p-4 rounded-lg max-w-xl w-full">
      <!-- Header -->
      <div class="flex justify-between items-center mb-4">
        <h2 class="text-2xl font-bold text-white">Sentence Explanation</h2>
        <!-- Close button (X) -->
        <button @click="modalStore.closeModal" class="text-gray-400 hover:text-white focus:outline-none">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="h-6 w-6">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
          </svg>
        </button>
      </div>

      <!-- Body -->
      <div class="text-left p-2">
        <div v-if="modalStore.modalLoading" class="text-gray-400">Loading...</div>
        <div v-if="modalStore.modalError" class="text-red-500 mt-4" v-text="modalStore.modalError" />
        <div v-if="modalStore.modalExplanation" class="text-gray-400" v-text="modalStore.modalExplanation" />
      </div>

      <!-- Horizontal Line (hr) -->
      <hr class="my-4 border-t border-gray-600">

      <!-- Footer -->
      <div class="flex justify-between items-center mt-5">
        <span class="text-gray-400 text-sm">Generated by ChatGPT</span>
        <button 
          @click="modalStore.closeModal"
          class="p-2 bg-blue-500 text-white rounded hover:bg-blue-600 focus:outline-none">
          Close
        </button>
      </div>
    </div>
  </div>
</template>